SERVER_IP = "192.168.56.110"
SERVER_NAME = "fcatinauS"
cpus           = ENV['CPUS'] || 2
memory         = ENV['MEMORY'] || 2048
BOX            = ENV['VERSION'] || "generic/alpine38"

Vagrant.configure("2") do |config|

        config.vm.box = BOX
        config.vm.provider "virtualbox" do |vb|
          vb.memory = memory # Need to up the size or vboxmanage return an error
          vb.cpus = cpus
        end

        config.vm.define SERVER_NAME do |fcatinauS|
            fcatinauS.vm.hostname = SERVER_NAME
            fcatinauS.vm.synced_folder ".", "/vagrant"
            fcatinauS.vm.network "private_network", ip: SERVER_IP
            fcatinauS.vm.provision "shell", privileged: true, path: "./scripts/k3s_config.sh", args: [SERVER_IP]
        end
    end