SERVER_IP = "192.168.56.110"
SERVER_NAME = "viportenS"
cpus           = ENV['CPUS'] || 2
memory         = ENV['MEMORY'] || 2048
BOX            = ENV['VERSION'] || "centos/8"

Vagrant.configure("2") do |config|

        config.vm.box = BOX
        config.vm.provider "virtualbox" do |vb|
          vb.memory = memory # Need to up the size or vboxmanage return an error
          vb.cpus = cpus
        end

        config.vm.define SERVER_NAME do |viportenS|
            viportenS.vm.network "forwarded_port", guest: 80, host: 80
            viportenS.vm.hostname = SERVER_NAME
            viportenS.vm.synced_folder ".", "/vagrant"
            viportenS.vm.network "private_network", ip: SERVER_IP
            viportenS.vm.provision "shell", privileged: true, path: "./scripts/k3s_config.sh", args: [SERVER_IP]
        end
    end