Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine38"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048 # Need to up the size or vboxmanage return an error
    vb.cpus = 1
  end

  # Server vm
  config.vm.define "fcatinauS" do |fcatinauS|
    fcatinauS.vm.hostname = "fcatinauS" # Define the hostname of the vm
    fcatinauS.vm.synced_folder ".", "/vagrant"  # Is the same of the volume for docker
    fcatinauS.vm.network "private_network", ip: "192.168.56.110" # Dfine the type of network and the ip address of the vm
    fcatinauS.vm.provision "shell", privileged: true, path: "config/server.sh", args: ["192.168.56.110"] # Launch a cmd inside the vm at launch
  end

  # # Worker vm
  # config.vm.define "fcatinauSW" do |fcatinauSW|
  #     fcatinauSW.vm.hostname = "fcatinauSW"
  #     fcatinauSW.vm.synced_folder ".", "/vagrant"
  #     fcatinauSW.vm.network "private_network", ip: 192,168,56,111
  #     fcatinauSW.vm.provision "shell", privileged: true, path: "scripts/worker.sh", args: ["192.168.56.110", "192.168.56.111"]
  # end

end
