
cpus           = ENV['CPUS'] || 2
memory         = ENV['MEMORY'] || 2048

BOX            = ENV['VERSION'] || "generic/alpine37" # Check for mprobably modif the version of alpine because k3s is not working in 38
SERVER_NAME    = "fcatinauS"
WORKER_NAME    = "fcatinauSW"
SERVER_IP      = "192.168.56.110"
WORKER_IP      = "192.168.56.111"
Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.provider "virtualbox" do |vb|
    vb.memory = memory # Need to up the size or vboxmanage return an error
    vb.cpus = cpus
  end

  # # Server vm
  config.vm.define SERVER_NAME do |fcatinauS|
    fcatinauS.vm.hostname = SERVER_NAME # Define the hostname of the vm
    fcatinauS.vm.synced_folder "config/", "/vagrant"  # Is the same of the volume for docker
    fcatinauS.vm.network "private_network", ip: SERVER_IP # Dfine the type of network and the ip address of the vm
    fcatinauS.vm.provision "shell", privileged: true, path: "config/server.sh", args: [SERVER_IP] # Launch a cmd inside the vm at launch
  end

  # # Worker vm
  config.vm.define WORKER_NAME do |fcatinauSW|
      fcatinauSW.vm.hostname = WORKER_NAME
      fcatinauSW.vm.synced_folder "config/", "/vagrant"
      fcatinauSW.vm.network "private_network", ip: WORKER_IP
      fcatinauSW.vm.provision "shell", privileged: true, path: "config/worker.sh", args: [SERVER_IP , WORKER_IP]
  end

end
