---
apiVersion: v1
kind: Service
metadata:
  name: app-1
  labels:
    app: app-1
spec:
  type: NodePort
  selector:
    app: app-1
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-2
  labels:
    app: app-2
spec:
  selector:
    app: app-2
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-3
  labels:
    app: app-3
spec:
  selector:
    app: app-3
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
---