SERVER_IP = "192.168.56.110"
SERVER_NAME = "fcatinauS"
cpus           = ENV['CPUS'] || 6
memory         = ENV['MEMORY'] || 6144
BOX            = ENV['VERSION'] || "ubuntu/lunar64"

Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.provider "virtualbox" do |vb|
    vb.memory = memory # Need to up the size or vboxmanage return an error
    vb.cpus = cpus
  end

  config.vm.define SERVER_NAME do |fcatinauS|
      fcatinauS.vm.hostname = SERVER_NAME
      fcatinauS.vm.synced_folder ".", "/vagrant"
      fcatinauS.vm.network "private_network", ip: SERVER_IP
      fcatinauS.vm.provision "shell", privileged: true, path: "install/k3d_dependency.sh"
      fcatinauS.vm.provision "shell", privileged: true, path: "install/setup.sh"
      fcatinauS.vm.provision "shell", privileged: true, path: "install/helm.sh"
  end
end