apiVersion: argoproj.io/v1apha1
kind: Deployment
metadata:
  name: wil42/playground
  namespace: argocd
spec:
  project: default
  source :
    repoURL: # link to github
    targetRevision: HEAD
    path: dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  
