apiVersion: argoproj.io/v1apha1
kind: Application
metadata:
  name: wil42/playground
  namespace: argocd
spec:
  project: default
  source :
    repoURL: https://github.com/Balgor18/viporten_IOT_P3.git # link to github
    targetRevision: HEAD
    path: dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncOption:
    automated:
      seflHeal:true
      prune:true
  
